# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Minnnning's log data

tagline: 공부 좀 하자
about: papap
description: >- # this means to ignore newlines until "baseurl:"
  Swift and Python
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minnnning.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: 6alswjd6@gmail.com
twitter_username: jekyllrb
github_username:  Minnnning

paginate: 7
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""  # 사이트 전반에 적용
      type: "posts"  # 모든 포스트에 적용
    values:
      layout: "post"  # 기본 레이아웃을 'post'로 설정


# Build settings
remote_theme: zivhub/monophase

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

